name: Terragrunt Plan

on: [pull_request]
#  push:
#    branches:
#      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [dev]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Terragrunt
        run: |
          # Replace the URL with the download URL for the latest Terragrunt version
          curl -LO https://github.com/gruntwork-io/terragrunt/releases/download/vX.X.X/terragrunt_linux_amd64
          chmod +x terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2 # Replace with your desired AWS region

      - name: Initialize Terragrunt
        run: |
          cd terraform/deployment/${{ matrix.environment }}/us-west-2/applications/simple-vpc
          terragrunt init

      - name: Generate Terragrunt plan
        run: |
          cd terraform/deployment/${{ matrix.environment }}/us-west-2/applications/simple-vpc
          terragrunt plan --out=tfplan

      - name: Save Terragrunt plan artifact
        uses: actions/upload-artifact@v2
        with:
          name: terragrunt-plan-${{ matrix.environment }}
          path: terraform/deployment/${{ matrix.environment }}/us-west-2/applications/simple-vpc/tfplan
